### ISSUE TITLE
Planned release date

### ISSUE THREAD

**Issue by Wallabeng** [monumentjs/core#34]
Hello!

I guess this library is not yet released on npm right? (at least I can't find it)
If not, is there any planned release date?

Thanks in advance!

**Comment by avchugaev** [comment]
Hello, @Wallabeng !
It's not yet released on NPM, you are right. I keep working on it.
Please tell me, which functionality (modules) you need most of all?

**Comment by Wallabeng** [comment]
The uri module would be of most interest to us at the moment.
As it seems to be very handy and I didn't find anything comparable.

**Comment by avchugaev** [comment]
Thank you, Marcel. 
You can contact me in Slack for more discussions ([invite link](https://join.slack.com/t/monumentjs/shared_invite/enQtNDY1ODA1MTExMzQ4LTI0MjllODEwOTk5MjM0NGIwY2YwNzVjNDU3YjEwYzYwYTNjMmI0NjFkNmNjMDFlMjA1NzgzODk0NjcxZTc4NjM))

I have some plans about this project:
1. Stabilization of `core` package (more tests)
2. Stabilization of `url` package
3. Extract repositories - one repo per package
4. Publishing to NPM

**Comment by avchugaev** [comment]
So if you interested in `uri` package for now, I think it can be published until next Monday, after some polishing. Docs will come up later.

**Comment by Wallabeng** [comment]
Cool! This would be fine with me.
Thanks a lot for your fast response!

**Comment by avchugaev** [comment]
@Wallabeng, packages already available on NPM.

- https://www.npmjs.com/package/@monument/core
- https://www.npmjs.com/package/@monument/uri

You can find API reference here:
- All: https://monumentjs.github.io/api/index.html
- URI: https://monumentjs.github.io/api/classes/uri.html
- URI parser: https://monumentjs.github.io/api/classes/uriparser.html

More documentation for published packages will come soon.

You may [join us on Slack](https://join.slack.com/t/monumentjs/shared_invite/enQtNDY1ODA1MTExMzQ4LTI0MjllODEwOTk5MjM0NGIwY2YwNzVjNDU3YjEwYzYwYTNjMmI0NjFkNmNjMDFlMjA1NzgzODk0NjcxZTc4NjM) to be aware what's going on.

**Comment by Wallabeng** [comment]
Thanks a lot!
